spring:
  datasource:
    url: jdbc:mysql://mysql-378cc660-awaisbrohi000-4804.c.aivencloud.com:26188/defaultdb
    username: avnadmin
    password: AVNS_LFZ1aHcRw0fhXuopnRF
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  show-sql: true